#!/usr/bin/env ruby
# This command will automatically be run when you run "rails" with Rails 3 gems installed from the root of your application.

load File.expand_path('../../spec/dummy/script/rails',  __FILE__)
